name: omero-guide-ilastik
channels:
  - conda-forge
  - ilastik-forge
  - nodefaults
dependencies:
  - python==3.9.*
  - omero-py==5.19.*
  - pip
  - ipywidgets==7.8.5
  - ilastik-forge::ilastik-core==1.4.1b22
  - ipykernel==6.29.5
  - yapsy==1.12.2
  - ome-zarr==0.9.0
